package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;

/**
 * Anh generated by hbm2java
 */
public class Anh implements java.io.Serializable {

	private Integer maAnh;
	private PhieuDangPhong phieuDangPhong;
	private Serializable duongDan;

	public Anh() {
	}

	public Anh(Serializable duongDan) {
		this.duongDan = duongDan;
	}

	public Anh(PhieuDangPhong phieuDangPhong, Serializable duongDan) {
		this.phieuDangPhong = phieuDangPhong;
		this.duongDan = duongDan;
	}

	public Integer getMaAnh() {
		return this.maAnh;
	}

	public void setMaAnh(Integer maAnh) {
		this.maAnh = maAnh;
	}

	public PhieuDangPhong getPhieuDangPhong() {
		return this.phieuDangPhong;
	}

	public void setPhieuDangPhong(PhieuDangPhong phieuDangPhong) {
		this.phieuDangPhong = phieuDangPhong;
	}

	public Serializable getDuongDan() {
		return this.duongDan;
	}

	public void setDuongDan(Serializable duongDan) {
		this.duongDan = duongDan;
	}

}
