package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Anh generated by hbm2java
 */
@Entity
@Table(name = "ANH")
public class Anh implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ma_anh")
	private Integer maAnh;

	@JoinColumn(name = "ma_phieu_dang")
	@ManyToOne
	private PhieuDangPhong phieuDangPhong;

	@Column(name = "duong_dan")
	private Serializable duongDan;

	public Anh() {
	}

	public Anh(Serializable duongDan) {
		this.duongDan = duongDan;
	}

	public Anh(PhieuDangPhong phieuDangPhong, Serializable duongDan) {
		this.phieuDangPhong = phieuDangPhong;
		this.duongDan = duongDan;
	}

	public Integer getMaAnh() {
		return this.maAnh;
	}

	public void setMaAnh(Integer maAnh) {
		this.maAnh = maAnh;
	}

	public PhieuDangPhong getPhieuDangPhong() {
		return this.phieuDangPhong;
	}

	public void setPhieuDangPhong(PhieuDangPhong phieuDangPhong) {
		this.phieuDangPhong = phieuDangPhong;
	}

	public Serializable getDuongDan() {
		return this.duongDan;
	}

	public void setDuongDan(Serializable duongDan) {
		this.duongDan = duongDan;
	}

}
