package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

//import java.io.Serializable;
import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

//import org.hibernate.annotations.Type;

/**
 * ChuPhong generated by hbm2java
 */
@Entity
@Table(name="CHU_PHONG")
public class ChuPhong implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@Column(name = "so_CMND")
	private String soCmnd;
	
	@Column(name = "ho_ten")
	private String hoTen;

	@Column(name = "so_dien_thoai")
	private String soDienThoai;

	@Column(name = "dia_chi")
	private String diaChi;

	@Column(name = "gioi_tinh")
	private Boolean gioiTinh;

	@Column(name = "ngay_sinh")
//	@Type(type ="com.laptrinhnangcao.moigioinhatro.models.DateHibernateUserType")
	private Date ngaySinh;

	@Column(name = "ten_dang_nhap")
	private String tenDangNhap;

//	@Column
	@OneToMany(mappedBy = "chuPhong")
	private Set<PhieuDangPhong> phieuDangPhongs = new HashSet<PhieuDangPhong>(0);

	public ChuPhong() {
	}

	public ChuPhong(String soCmnd, String hoTen, String soDienThoai, String diaChi, boolean gioiTinh,
			String tenDangNhap) {
		this.soCmnd = soCmnd;
		this.hoTen = hoTen;
		this.soDienThoai = soDienThoai;
		this.diaChi = diaChi;
		this.gioiTinh = gioiTinh;
		this.tenDangNhap = tenDangNhap;
	}

	public ChuPhong(String soCmnd, String hoTen, String soDienThoai, String diaChi, boolean gioiTinh,
			Date ngaySinh, String tenDangNhap, Set<PhieuDangPhong> phieuDangPhongs) {
		this.soCmnd = soCmnd;
		this.hoTen = hoTen;
		this.soDienThoai = soDienThoai;
		this.diaChi = diaChi;
		this.gioiTinh = gioiTinh;
		this.ngaySinh = ngaySinh;
		this.tenDangNhap = tenDangNhap;
		this.phieuDangPhongs = phieuDangPhongs;
	}

	public String getSoCmnd() {
		return this.soCmnd;
	}

	public void setSoCmnd(String soCmnd) {
		this.soCmnd = soCmnd;
	}

	public String getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}

	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	public String getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public boolean isGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	public Set<PhieuDangPhong> getPhieuDangPhongs() {
		return this.phieuDangPhongs;
	}

	public void setPhieuDangPhongs(Set<PhieuDangPhong> phieuDangPhongs) {
		this.phieuDangPhongs = phieuDangPhongs;
	}

}
