package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ChuPhong generated by hbm2java
 */
public class ChuPhong implements java.io.Serializable {

	private String soCmnd;
	private Serializable hoTen;
	private String soDienThoai;
	private Serializable diaChi;
	private boolean gioiTinh;
	private Date ngaySinh;
	private String tenDangNhap;
	private Set phieuDangPhongs = new HashSet(0);

	public ChuPhong() {
	}

	public ChuPhong(String soCmnd, Serializable hoTen, String soDienThoai, Serializable diaChi, boolean gioiTinh,
			String tenDangNhap) {
		this.soCmnd = soCmnd;
		this.hoTen = hoTen;
		this.soDienThoai = soDienThoai;
		this.diaChi = diaChi;
		this.gioiTinh = gioiTinh;
		this.tenDangNhap = tenDangNhap;
	}

	public ChuPhong(String soCmnd, Serializable hoTen, String soDienThoai, Serializable diaChi, boolean gioiTinh,
			Date ngaySinh, String tenDangNhap, Set phieuDangPhongs) {
		this.soCmnd = soCmnd;
		this.hoTen = hoTen;
		this.soDienThoai = soDienThoai;
		this.diaChi = diaChi;
		this.gioiTinh = gioiTinh;
		this.ngaySinh = ngaySinh;
		this.tenDangNhap = tenDangNhap;
		this.phieuDangPhongs = phieuDangPhongs;
	}

	public String getSoCmnd() {
		return this.soCmnd;
	}

	public void setSoCmnd(String soCmnd) {
		this.soCmnd = soCmnd;
	}

	public Serializable getHoTen() {
		return this.hoTen;
	}

	public void setHoTen(Serializable hoTen) {
		this.hoTen = hoTen;
	}

	public String getSoDienThoai() {
		return this.soDienThoai;
	}

	public void setSoDienThoai(String soDienThoai) {
		this.soDienThoai = soDienThoai;
	}

	public Serializable getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(Serializable diaChi) {
		this.diaChi = diaChi;
	}

	public boolean isGioiTinh() {
		return this.gioiTinh;
	}

	public void setGioiTinh(boolean gioiTinh) {
		this.gioiTinh = gioiTinh;
	}

	public Date getNgaySinh() {
		return this.ngaySinh;
	}

	public void setNgaySinh(Date ngaySinh) {
		this.ngaySinh = ngaySinh;
	}

	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	public Set getPhieuDangPhongs() {
		return this.phieuDangPhongs;
	}

	public void setPhieuDangPhongs(Set phieuDangPhongs) {
		this.phieuDangPhongs = phieuDangPhongs;
	}

}
