package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * KhuVuc generated by hbm2java
 */
public class KhuVuc implements java.io.Serializable {

	private Integer maKhuVuc;
	private Serializable tenKhuVuc;
	private Set phongs = new HashSet(0);

	public KhuVuc() {
	}

	public KhuVuc(Serializable tenKhuVuc, Set phongs) {
		this.tenKhuVuc = tenKhuVuc;
		this.phongs = phongs;
	}

	public Integer getMaKhuVuc() {
		return this.maKhuVuc;
	}

	public void setMaKhuVuc(Integer maKhuVuc) {
		this.maKhuVuc = maKhuVuc;
	}

	public Serializable getTenKhuVuc() {
		return this.tenKhuVuc;
	}

	public void setTenKhuVuc(Serializable tenKhuVuc) {
		this.tenKhuVuc = tenKhuVuc;
	}

	public Set getPhongs() {
		return this.phongs;
	}

	public void setPhongs(Set phongs) {
		this.phongs = phongs;
	}

}
