package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * LoaiPhong generated by hbm2java
 */
public class LoaiPhong implements java.io.Serializable {

	private Integer maLoaiPhong;
	private Serializable tenLoaiPhong;
	private Set phongs = new HashSet(0);

	public LoaiPhong() {
	}

	public LoaiPhong(Serializable tenLoaiPhong, Set phongs) {
		this.tenLoaiPhong = tenLoaiPhong;
		this.phongs = phongs;
	}

	public Integer getMaLoaiPhong() {
		return this.maLoaiPhong;
	}

	public void setMaLoaiPhong(Integer maLoaiPhong) {
		this.maLoaiPhong = maLoaiPhong;
	}

	public Serializable getTenLoaiPhong() {
		return this.tenLoaiPhong;
	}

	public void setTenLoaiPhong(Serializable tenLoaiPhong) {
		this.tenLoaiPhong = tenLoaiPhong;
	}

	public Set getPhongs() {
		return this.phongs;
	}

	public void setPhongs(Set phongs) {
		this.phongs = phongs;
	}

}
