package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * NguoiDung generated by hbm2java
 */
public class NguoiDung implements java.io.Serializable {

	private String tenDangNhap;
	private String matKhau;
	private Set quyenNguoiDungs = new HashSet(0);

	public NguoiDung() {
	}

	public NguoiDung(String tenDangNhap, String matKhau) {
		this.tenDangNhap = tenDangNhap;
		this.matKhau = matKhau;
	}

	public NguoiDung(String tenDangNhap, String matKhau, Set quyenNguoiDungs) {
		this.tenDangNhap = tenDangNhap;
		this.matKhau = matKhau;
		this.quyenNguoiDungs = quyenNguoiDungs;
	}

	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	public String getMatKhau() {
		return this.matKhau;
	}

	public void setMatKhau(String matKhau) {
		this.matKhau = matKhau;
	}

	public Set getQuyenNguoiDungs() {
		return this.quyenNguoiDungs;
	}

	public void setQuyenNguoiDungs(Set quyenNguoiDungs) {
		this.quyenNguoiDungs = quyenNguoiDungs;
	}

}
