package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

import java.util.HashSet;
import java.util.Set;

/**
 * NhomNguoiDung generated by hbm2java
 */
public class NhomNguoiDung implements java.io.Serializable {

	private Integer maNhomNguoiDung;
	private Quyen quyen;
	private String tenNhomNguoiDung;
	private Set quyenNguoiDungs = new HashSet(0);

	public NhomNguoiDung() {
	}

	public NhomNguoiDung(Quyen quyen, String tenNhomNguoiDung, Set quyenNguoiDungs) {
		this.quyen = quyen;
		this.tenNhomNguoiDung = tenNhomNguoiDung;
		this.quyenNguoiDungs = quyenNguoiDungs;
	}

	public Integer getMaNhomNguoiDung() {
		return this.maNhomNguoiDung;
	}

	public void setMaNhomNguoiDung(Integer maNhomNguoiDung) {
		this.maNhomNguoiDung = maNhomNguoiDung;
	}

	public Quyen getQuyen() {
		return this.quyen;
	}

	public void setQuyen(Quyen quyen) {
		this.quyen = quyen;
	}

	public String getTenNhomNguoiDung() {
		return this.tenNhomNguoiDung;
	}

	public void setTenNhomNguoiDung(String tenNhomNguoiDung) {
		this.tenNhomNguoiDung = tenNhomNguoiDung;
	}

	public Set getQuyenNguoiDungs() {
		return this.quyenNguoiDungs;
	}

	public void setQuyenNguoiDungs(Set quyenNguoiDungs) {
		this.quyenNguoiDungs = quyenNguoiDungs;
	}

}
