package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PhieuDangPhong generated by hbm2java
 */
public class PhieuDangPhong implements java.io.Serializable {
	
	private Integer maPhieuDang;
	private ChuPhong chuPhong;
	private Phong phong;
	private TienIch tienIch;
	private int tienGiuCho;
	private int tienDatCoc;
	private int tienThue;
	private int tienDien;
	private int tienNuoc;
	private Date ngayDang;
	private Boolean trangThai;	// van dang tim nguoi thue
	private Set anhs = new HashSet(0);

	public PhieuDangPhong() {
	}

	public PhieuDangPhong(int tienGiuCho, int tienDatCoc, int tienThue, int tienDien, int tienNuoc) {
		this.tienGiuCho = tienGiuCho;
		this.tienDatCoc = tienDatCoc;
		this.tienThue = tienThue;
		this.tienDien = tienDien;
		this.tienNuoc = tienNuoc;
	}

	public PhieuDangPhong(ChuPhong chuPhong, Phong phong, TienIch tienIch, int tienGiuCho, int tienDatCoc, int tienThue,
			int tienDien, int tienNuoc, Date ngayDang, Boolean trangThai, Set anhs) {
		this.chuPhong = chuPhong;
		this.phong = phong;
		this.tienIch = tienIch;
		this.tienGiuCho = tienGiuCho;
		this.tienDatCoc = tienDatCoc;
		this.tienThue = tienThue;
		this.tienDien = tienDien;
		this.tienNuoc = tienNuoc;
		this.ngayDang = ngayDang;
		this.trangThai = trangThai;
		this.anhs = anhs;
	}

	public Integer getMaPhieuDang() {
		return this.maPhieuDang;
	}

	public void setMaPhieuDang(Integer maPhieuDang) {
		this.maPhieuDang = maPhieuDang;
	}

	public ChuPhong getChuPhong() {
		return this.chuPhong;
	}

	public void setChuPhong(ChuPhong chuPhong) {
		this.chuPhong = chuPhong;
	}

	public Phong getPhong() {
		return this.phong;
	}

	public void setPhong(Phong phong) {
		this.phong = phong;
	}

	public TienIch getTienIch() {
		return this.tienIch;
	}

	public void setTienIch(TienIch tienIch) {
		this.tienIch = tienIch;
	}

	public int getTienGiuCho() {
		return this.tienGiuCho;
	}

	public void setTienGiuCho(int tienGiuCho) {
		this.tienGiuCho = tienGiuCho;
	}

	public int getTienDatCoc() {
		return this.tienDatCoc;
	}

	public void setTienDatCoc(int tienDatCoc) {
		this.tienDatCoc = tienDatCoc;
	}

	public int getTienThue() {
		return this.tienThue;
	}

	public void setTienThue(int tienThue) {
		this.tienThue = tienThue;
	}

	public int getTienDien() {
		return this.tienDien;
	}

	public void setTienDien(int tienDien) {
		this.tienDien = tienDien;
	}

	public int getTienNuoc() {
		return this.tienNuoc;
	}

	public void setTienNuoc(int tienNuoc) {
		this.tienNuoc = tienNuoc;
	}

	public Date getNgayDang() {
		return this.ngayDang;
	}

	public void setNgayDang(Date ngayDang) {
		this.ngayDang = ngayDang;
	}

	public Boolean getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(Boolean trangThai) {
		this.trangThai = trangThai;
	}

	public Set getAnhs() {
		return this.anhs;
	}

	public void setAnhs(Set anhs) {
		this.anhs = anhs;
	}

}
