package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phong generated by hbm2java
 */
@Entity
@Table(name="PHONG")
public class Phong implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ma_phong")
	private Integer maPhong;

	@JoinColumn(name = "ma_khu_vuc")
	@ManyToOne
	private KhuVuc khuVuc;

	@JoinColumn(name = "ma_loai_phong")
	@ManyToOne
	private LoaiPhong loaiPhong;

	@Column(name = "ten_phong")
	private String tenPhong;

	@Column(name = "dien_tich")
	private Double dienTich;

	@Column(name = "suc_chua")
	private Integer sucChua;

	@Column(name = "dia_chi")
	private String diaChi;

	@Column(name = "mo_ta_them")
	private String moTaThem;
//
//	@Column(name = "ma_phieu_dang_phong")
	@OneToMany(mappedBy = "phong")
	private Set<PhieuDangPhong> phieuDangPhongs = new HashSet<PhieuDangPhong>(0);

	public Phong() {
	}

	public Phong(String tenPhong, double dienTich, String diaChi) {
		this.tenPhong = tenPhong;
		this.dienTich = dienTich;
		this.diaChi = diaChi;
	}

	public Phong(KhuVuc khuVuc, LoaiPhong loaiPhong, String tenPhong, double dienTich, Integer sucChua,
			String diaChi, String moTaThem, Set<PhieuDangPhong> phieuDangPhongs) {
		this.khuVuc = khuVuc;
		this.loaiPhong = loaiPhong;
		this.tenPhong = tenPhong;
		this.dienTich = dienTich;
		this.sucChua = sucChua;
		this.diaChi = diaChi;
		this.moTaThem = moTaThem;
		this.phieuDangPhongs = phieuDangPhongs;
	}

	public Integer getMaPhong() {
		return this.maPhong;
	}

	public void setMaPhong(Integer maPhong) {
		this.maPhong = maPhong;
	}

	public KhuVuc getKhuVuc() {
		return this.khuVuc;
	}

	public void setKhuVuc(KhuVuc khuVuc) {
		this.khuVuc = khuVuc;
	}

	public LoaiPhong getLoaiPhong() {
		return this.loaiPhong;
	}

	public void setLoaiPhong(LoaiPhong loaiPhong) {
		this.loaiPhong = loaiPhong;
	}

	public Serializable getTenPhong() {
		return this.tenPhong;
	}

	public void setTenPhong(String tenPhong) {
		this.tenPhong = tenPhong;
	}

	public double getDienTich() {
		return this.dienTich;
	}

	public void setDienTich(double dienTich) {
		this.dienTich = dienTich;
	}

	public Integer getSucChua() {
		return this.sucChua;
	}

	public void setSucChua(Integer sucChua) {
		this.sucChua = sucChua;
	}

	public Serializable getDiaChi() {
		return this.diaChi;
	}

	public void setDiaChi(String diaChi) {
		this.diaChi = diaChi;
	}

	public Serializable getMoTaThem() {
		return this.moTaThem;
	}

	public void setMoTaThem(String moTaThem) {
		this.moTaThem = moTaThem;
	}

	public Set<PhieuDangPhong> getPhieuDangPhongs() {
		return this.phieuDangPhongs;
	}

	public void setPhieuDangPhongs(Set<PhieuDangPhong> phieuDangPhongs) {
		this.phieuDangPhongs = phieuDangPhongs;
	}

}
