package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

/**
 * QuyenNguoiDung generated by hbm2java
 */
public class QuyenNguoiDung implements java.io.Serializable {

	private QuyenNguoiDungId id;
	private NguoiDung nguoiDung;
	private NhomNguoiDung nhomNguoiDung;

	public QuyenNguoiDung() {
	}

	public QuyenNguoiDung(QuyenNguoiDungId id, NguoiDung nguoiDung, NhomNguoiDung nhomNguoiDung) {
		this.id = id;
		this.nguoiDung = nguoiDung;
		this.nhomNguoiDung = nhomNguoiDung;
	}

	public QuyenNguoiDungId getId() {
		return this.id;
	}

	public void setId(QuyenNguoiDungId id) {
		this.id = id;
	}

	public NguoiDung getNguoiDung() {
		return this.nguoiDung;
	}

	public void setNguoiDung(NguoiDung nguoiDung) {
		this.nguoiDung = nguoiDung;
	}

	public NhomNguoiDung getNhomNguoiDung() {
		return this.nhomNguoiDung;
	}

	public void setNhomNguoiDung(NhomNguoiDung nhomNguoiDung) {
		this.nhomNguoiDung = nhomNguoiDung;
	}

}
