package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Quyen generated by hbm2java
 */
public class Quyen implements java.io.Serializable {

	private Integer maQuyen;
	private Serializable tenQuyen;
	private int quyenTruyCap;
	private Set nhomNguoiDungs = new HashSet(0);

	public Quyen() {
	}

	public Quyen(Serializable tenQuyen, int quyenTruyCap) {
		this.tenQuyen = tenQuyen;
		this.quyenTruyCap = quyenTruyCap;
	}

	public Quyen(Serializable tenQuyen, int quyenTruyCap, Set nhomNguoiDungs) {
		this.tenQuyen = tenQuyen;
		this.quyenTruyCap = quyenTruyCap;
		this.nhomNguoiDungs = nhomNguoiDungs;
	}

	public Integer getMaQuyen() {
		return this.maQuyen;
	}

	public void setMaQuyen(Integer maQuyen) {
		this.maQuyen = maQuyen;
	}

	public Serializable getTenQuyen() {
		return this.tenQuyen;
	}

	public void setTenQuyen(Serializable tenQuyen) {
		this.tenQuyen = tenQuyen;
	}

	public int getQuyenTruyCap() {
		return this.quyenTruyCap;
	}

	public void setQuyenTruyCap(int quyenTruyCap) {
		this.quyenTruyCap = quyenTruyCap;
	}

	public Set getNhomNguoiDungs() {
		return this.nhomNguoiDungs;
	}

	public void setNhomNguoiDungs(Set nhomNguoiDungs) {
		this.nhomNguoiDungs = nhomNguoiDungs;
	}

}
