package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;

/**
 * Quyen generated by hbm2java
 */
public class Quyen implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ma_quyen")
	private Integer maQuyen;
	
	@Column(name = "ten_quyen")
	private String tenQuyen;
	
	@Column(name = "quyen_truy_cap")
	private Integer quyenTruyCap;
	
	@OneToMany(mappedBy = "quyen")
	private Set<NhomNguoiDung> nhomNguoiDungs = new HashSet<NhomNguoiDung>(0);

	public Quyen() {
	}

	public Quyen(String tenQuyen, int quyenTruyCap) {
		this.tenQuyen = tenQuyen;
		this.quyenTruyCap = quyenTruyCap;
	}

	public Quyen(String tenQuyen, int quyenTruyCap, Set<NhomNguoiDung> nhomNguoiDungs) {
		this.tenQuyen = tenQuyen;
		this.quyenTruyCap = quyenTruyCap;
		this.nhomNguoiDungs = nhomNguoiDungs;
	}

	public Integer getMaQuyen() {
		return this.maQuyen;
	}

	public void setMaQuyen(Integer maQuyen) {
		this.maQuyen = maQuyen;
	}

	public Serializable getTenQuyen() {
		return this.tenQuyen;
	}

	public void setTenQuyen(String tenQuyen) {
		this.tenQuyen = tenQuyen;
	}

	public int getQuyenTruyCap() {
		return this.quyenTruyCap;
	}

	public void setQuyenTruyCap(int quyenTruyCap) {
		this.quyenTruyCap = quyenTruyCap;
	}

	public Set<NhomNguoiDung> getNhomNguoiDungs() {
		return this.nhomNguoiDungs;
	}

	public void setNhomNguoiDungs(Set<NhomNguoiDung> nhomNguoiDungs) {
		this.nhomNguoiDungs = nhomNguoiDungs;
	}

}
