package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

////import javax.persistence.Column;
//import javax.persistence.GeneratedValue;
//import javax.persistence.GenerationType;
import javax.persistence.*;

/**
 * QuyenNguoiDung generated by hbm2java
 */
public class QuyenNguoiDung implements java.io.Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

//	@Id
//	@GeneratedValue(strategy = GenerationType.IDENTITY)
//	transient private QuyenNguoiDungId id;
	
	@JoinColumn(name = "ten_dang_nhap")
	@ManyToOne
	private NguoiDung nguoiDung;
	
	@JoinColumn(name = "ma_nhom_nguoi_dung")
	@ManyToOne
	private NhomNguoiDung nhomNguoiDung;

	public QuyenNguoiDung() {
	}

	public QuyenNguoiDung(NguoiDung nguoiDung, NhomNguoiDung nhomNguoiDung) {
		this.nguoiDung = nguoiDung;
		this.nhomNguoiDung = nhomNguoiDung;
	}

	public NguoiDung getNguoiDung() {
		return this.nguoiDung;
	}

	public void setNguoiDung(NguoiDung nguoiDung) {
		this.nguoiDung = nguoiDung;
	}

	public NhomNguoiDung getNhomNguoiDung() {
		return this.nhomNguoiDung;
	}

	public void setNhomNguoiDung(NhomNguoiDung nhomNguoiDung) {
		this.nhomNguoiDung = nhomNguoiDung;
	}

}
