package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

/**
 * QuyenNguoiDungId generated by hbm2java
 */
public class QuyenNguoiDungId implements java.io.Serializable {

	private int maNhomNguoiDung;
	private String tenDangNhap;

	public QuyenNguoiDungId() {
	}

	public QuyenNguoiDungId(int maNhomNguoiDung, String tenDangNhap) {
		this.maNhomNguoiDung = maNhomNguoiDung;
		this.tenDangNhap = tenDangNhap;
	}

	public int getMaNhomNguoiDung() {
		return this.maNhomNguoiDung;
	}

	public void setMaNhomNguoiDung(int maNhomNguoiDung) {
		this.maNhomNguoiDung = maNhomNguoiDung;
	}

	public String getTenDangNhap() {
		return this.tenDangNhap;
	}

	public void setTenDangNhap(String tenDangNhap) {
		this.tenDangNhap = tenDangNhap;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof QuyenNguoiDungId))
			return false;
		QuyenNguoiDungId castOther = (QuyenNguoiDungId) other;

		return (this.getMaNhomNguoiDung() == castOther.getMaNhomNguoiDung())
				&& ((this.getTenDangNhap() == castOther.getTenDangNhap())
						|| (this.getTenDangNhap() != null && castOther.getTenDangNhap() != null
								&& this.getTenDangNhap().equals(castOther.getTenDangNhap())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMaNhomNguoiDung();
		result = 37 * result + (getTenDangNhap() == null ? 0 : this.getTenDangNhap().hashCode());
		return result;
	}

}
