package com.laptrinhnangcao.moigioinhatro.entities;
// Generated Dec 6, 2020, 3:59:30 PM by Hibernate Tools 5.4.21.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * TienIch generated by hbm2java
 */
public class TienIch implements java.io.Serializable {

	private Integer maTienIch;
	private Integer soLuongMayLanh;
	private Integer soLuongWcRieng;
	private Boolean coChoDeXe;
	private Integer soLuongTuLanh;
	private Integer soLuongTiVi;
	private Integer soLuongTuQuanAo;
	private Integer soLuongMayNuocNong;
	private Serializable tienIchRieng;
	private Set phieuDangPhongs = new HashSet(0);

	public TienIch() {
	}

	public TienIch(Integer soLuongMayLanh, Integer soLuongWcRieng, Boolean coChoDeXe, Integer soLuongTuLanh,
			Integer soLuongTiVi, Integer soLuongTuQuanAo, Integer soLuongMayNuocNong, Serializable tienIchRieng,
			Set phieuDangPhongs) {
		this.soLuongMayLanh = soLuongMayLanh;
		this.soLuongWcRieng = soLuongWcRieng;
		this.coChoDeXe = coChoDeXe;
		this.soLuongTuLanh = soLuongTuLanh;
		this.soLuongTiVi = soLuongTiVi;
		this.soLuongTuQuanAo = soLuongTuQuanAo;
		this.soLuongMayNuocNong = soLuongMayNuocNong;
		this.tienIchRieng = tienIchRieng;
		this.phieuDangPhongs = phieuDangPhongs;
	}

	public Integer getMaTienIch() {
		return this.maTienIch;
	}

	public void setMaTienIch(Integer maTienIch) {
		this.maTienIch = maTienIch;
	}

	public Integer getSoLuongMayLanh() {
		return this.soLuongMayLanh;
	}

	public void setSoLuongMayLanh(Integer soLuongMayLanh) {
		this.soLuongMayLanh = soLuongMayLanh;
	}

	public Integer getSoLuongWcRieng() {
		return this.soLuongWcRieng;
	}

	public void setSoLuongWcRieng(Integer soLuongWcRieng) {
		this.soLuongWcRieng = soLuongWcRieng;
	}

	public Boolean getCoChoDeXe() {
		return this.coChoDeXe;
	}

	public void setCoChoDeXe(Boolean coChoDeXe) {
		this.coChoDeXe = coChoDeXe;
	}

	public Integer getSoLuongTuLanh() {
		return this.soLuongTuLanh;
	}

	public void setSoLuongTuLanh(Integer soLuongTuLanh) {
		this.soLuongTuLanh = soLuongTuLanh;
	}

	public Integer getSoLuongTiVi() {
		return this.soLuongTiVi;
	}

	public void setSoLuongTiVi(Integer soLuongTiVi) {
		this.soLuongTiVi = soLuongTiVi;
	}

	public Integer getSoLuongTuQuanAo() {
		return this.soLuongTuQuanAo;
	}

	public void setSoLuongTuQuanAo(Integer soLuongTuQuanAo) {
		this.soLuongTuQuanAo = soLuongTuQuanAo;
	}

	public Integer getSoLuongMayNuocNong() {
		return this.soLuongMayNuocNong;
	}

	public void setSoLuongMayNuocNong(Integer soLuongMayNuocNong) {
		this.soLuongMayNuocNong = soLuongMayNuocNong;
	}

	public Serializable getTienIchRieng() {
		return this.tienIchRieng;
	}

	public void setTienIchRieng(Serializable tienIchRieng) {
		this.tienIchRieng = tienIchRieng;
	}

	public Set getPhieuDangPhongs() {
		return this.phieuDangPhongs;
	}

	public void setPhieuDangPhongs(Set phieuDangPhongs) {
		this.phieuDangPhongs = phieuDangPhongs;
	}

}
